services:
  sysbox-agent:
    image: sysbox:latest
    container_name: sysbox-agent
    restart: unless-stopped
    depends_on:
      sysbox-api:
        condition: service_started
    entrypoint:
      - sysbox
    command:
      - agent
      - start
      - --identity
      - /var/lib/sysbox/agent/identity.json
      - --config
      - /etc/sysbox/sysbox.yaml
    volumes:
      - ${SYSBOX_HOST_DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
      - ${SYSBOX_HOST_HOME_DIR:-.sysbox/api}:/var/lib/sysbox
      - ${SYSBOX_HOST_CACHE_DIR:-~/.cache/sysbox}:/var/cache/sysbox
      - ./deploy/docker/sysbox.yaml:/etc/sysbox/sysbox.yaml:ro
    environment:
      SYSBOX_CONFIG: ${SYSBOX_CONFIG:-/etc/sysbox/sysbox.yaml}
      SYSBOX_API_TOKEN: ${SYSBOX_API_TOKEN:-}
      SYSBOX_STATE_BACKEND: ${SYSBOX_STATE_BACKEND:-postgres://${SYSBOX_POSTGRES_USERNAME:-sysbox}:${SYSBOX_POSTGRES_PASSWORD:-change-me}@sysbox-postgres:5432/${SYSBOX_POSTGRES_DATABASE:-sysbox}?sslmode=disable&topology={topology}}
      PATH: /opt/sysbox/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
